services:
  pythontos6-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/pythontos6-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
      - ${DEBUG_PORT1}:${DEBUG_PORT1}

  pythontos6:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/pythontos6:${TAG}
