name: Build & Deploy TorizonCore
on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    name: Build & Deploy
    container:
      image: torizonextras/torizon-dev:dev
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Get Host Absolute Workspace Path
        run: |
          echo "${{ github.workspace }}" >> abs-path
          cat abs-path

      - name: Initial Setup
        shell: xonsh {0}
        env:
          TASKS_DISABLE_INTERACTIVE_INPUT: "True"
          TASKS_OVERRIDE_ENV: "False"
          TORIZON_ARCH: "arm64"
          DOCKER_PSSWD: ${{ secrets.DOCKER_PSSWD }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          import os
          import json

          $RAISE_SUBPROC_ERROR = True
          $XONSH_SHOW_TRACEBACK = True
          $UPDATE_OS_ENVIRON = True

          with open(".vscode/settings.json") as f:
              settings = json.load(f)
              os.environ["TORIZON_ARCH"] = settings["torizon_arch"]
              if os.environ["TORIZON_ARCH"] == "aarch64":
                  os.environ["TORIZON_ARCH"] = "arm64"
              if os.environ["TORIZON_ARCH"] == "armhf":
                  os.environ["TORIZON_ARCH"] = "arm"

          with open(os.environ["GITHUB_ENV"], "a") as f:
              f.write(f"TORIZON_ARCH={os.environ['TORIZON_ARCH']}\n")

          xonsh ./.vscode/tasks.xsh run validate-pipeline-settings

      - name: Decode Credentials
        env:
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          echo $PLATFORM_CREDENTIALS | base64 -d > credentials.zip

      - name: Create and Publish Image
        shell: xonsh {0}
        env:
          TASKS_DISABLE_INTERACTIVE_INPUT: "True"
          TASKS_OVERRIDE_ENV: "False"
          TORIZON_ARCH: "arm64"
          DOCKER_PSSWD: ${{ secrets.DOCKER_PSSWD }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        run: |
          env

          xonsh ./.vscode/tasks.xsh run docker-login
          xonsh ./.vscode/tasks.xsh run run-torizon-binfmt
          xonsh ./.vscode/tasks.xsh run create-production-image
